import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const vazirFont = localFont({
   src: "./Vazirmatn-VariableFont_wght.ttf",
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={vazirFont.className}>
            {children}
         </body>
      </html>
   );
}
