import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const vazirFont = localFont({
    src: "./fonts/Vazirmatn-VariableFont_wght.ttf",
    variable: "--font-vazir",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="fa" dir="rtl">
            <body
                className={`${vazirFont.className} ${vazirFont.variable}`}
            >
                {children}
            </body>
        </html>
    );
}
